---
name: simplevanish
main: al3xdev\simplevanish\vanish
api:
- 3.12.0
mcpe-protocol:
- 390
version: "1.3.6 Beta"
author: al3xdev
commands:
  simplevanish:
    description: For Staff only! 
    permission: simplevanish.plugin.use
    aliases:
    - v
    - sv
permissions:
  simplevanish.plugin.use:
    description: simplevanish Permission to use the simplevanish plugin
    default: op
  simplevanish.plugin.see:
    description: simplevanish Permission to see other vanished user
    default: op
...
